config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  #

  root to: redirect('home')
  get 'home', to: 'pages#home', as: 'home'

  get 'animals', to: 'pages#index', as: 'animals'
end

app/models/animal.rb
# == Schema Information
#
# Table name: animals
#
#  id         :bigint           not null, primary key
#  location   :string
#  name       :string
#  species    :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Animal < ApplicationRecord
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def home
    render :home
  end

  def index
    @animals = Animal.all
    render :index
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  BOOTSTRAP_ALERT_CLASS = {
    'success' => 'alert-success',
    'error'   => 'alert-danger',
    'notice'  => 'alert-info',
    'alert'   => 'alert-danger',
    'warn'    => 'alert-warning'
  }.freeze

  def alert_class(flash_key)
    BOOTSTRAP_ALERT_CLASS.fetch(flash_key, 'alert-info')
  end
end

app/helpers/pages_helper.rb
# frozen_string_literal: true

module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MemphisZoo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/flash' %>

    <main role="main" class="container">
      <%= yield %>
    </main>
  </body>
</html>

app/views/pages/home.html.erb
<h1 class="text-center text-primary display-2">The Memphis Zoo</h1>

<p class="text-center h2 my-4 text-secondary">
  Meet Our Animals:
  <%= link_to 'Zoo Directory', animals_path %>

</p>

<%= image_tag 'zoo_map.jpeg', class: 'w-100 shadow-lg d-block mx-auto my-4', style: 'max-width: 64rem;' %>

app/views/pages/index.html.erb
<h1>Zoo Directory</h1>
 
<table class="table table-hover">
 
  <thead class="table-dark">
    <tr>
      <th>Name</th>
      <th>Species</th>
      <th>location</th>
    </tr>
  </thead>
 
  <tbody>
    <% @animals.each do |animal| %>
      <tr>
        <td><%= animal.name %></td>
        <td><%= animal.species %></td>
        <td><%= animal.location %></td>

      </tr>


    <% end %>
  </tbody>
 
</table>

<p>

  <%= link_to 'Home', root_path %>

</p>

app/views/shared/_flash.html.erb
<% flash.each do |key, message| %>
  <div class="alert <%= alert_class(key) %> alert-dismissible fade show" role="alert">
    <div class="text-center alert-message"><%= message %></div>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>